# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95e7053be8f9152e297acb9848961493dd1960eed2551ffec010f7a1e423f0d567d832593cf14cccf75dcc743fc35db1f9e6d22da784a14f2470b0633ffd7844

test:
  secret_key_base: ef66af96f324937a5cfdfe5080bbcf5bc2a62e47e601cd573ead51515fd8292c7e2aeb01f987720ad26e5d60cd2863af85b13483ed8eaea608c6b94728037f6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
